IT-2314 add flow logging
Sage-Bionetworks/synapse-docker-registry pull request #12
Opened 2024-12-19 23:08 UTC by brucehoff

AWS Config reports: 
> Ensure VPC flow logging is enabled in all VPCs

This PR adds it for the Synapse Docker registry

2024-12-23 18:20 UTC, zaro0508 commented on common/vpc_stack.py
> +FLOW_LOGS_BUCKET="sagebase-vpc-flow-logs-bucket-bucket-5lvxjv2gp37h"
there are already a bunch of VARs setup in `cdk.json`, like `VPC_CIDR_CONTEXT` why not follow the pattern and put this there as well?

2025-01-02 17:01 UTC, brucehoff commented on common/vpc_stack.py
> +FLOW_LOGS_BUCKET="sagebase-vpc-flow-logs-bucket-bucket-5lvxjv2gp37h"
To me, `cdk.json` is a place to store configuration that varies between deployments (dev, staging, prod).  This value is the same for all stacks.

2025-01-02 19:56 UTC, zaro0508 requested changes

2025-01-02 19:56 UTC, zaro0508 commented on common/vpc_stack.py
> +FLOW_LOGS_BUCKET="sagebase-vpc-flow-logs-bucket-bucket-5lvxjv2gp37h"
ohh, i see you are trying to setup sending to the central flow logs bucket in org-sagebase-logcentral account.

2025-01-02 19:56 UTC, zaro0508 commented on common/vpc_stack.py
> +        self.vpc.add_flow_log(f"{stack_id}-FlowLogS3",destination=ec2.FlowLogDestination.to_s3(bucket=bucket))
I don't think this is going to work because I believe this will require ECS to have access to the central `sagebase-vpc-flow-logs-bucket-bucket-5lvxjv2gp37h` bucket that's in a separate AWS account.   I could be wrong but I think you will need to setup cross account bucket access for this to work.

2025-01-02 20:57 UTC, brucehoff commented on common/vpc_stack.py
> +        self.vpc.add_flow_log(f"{stack_id}-FlowLogS3",destination=ec2.FlowLogDestination.to_s3(bucket=bucket))
We are already getting flow logs from Synapse prod (as well as many other accounts).

2025-01-02 23:20 UTC, zaro0508 commented
Actually you don't need to do this because we already setup VPC flow log aggregation at the organizations level.  Please take a look at issue IT-3721 for more info of the implementation.

2025-02-04 19:48 UTC, zaro0508 commented
done with https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/1331

2025-02-04 19:48 UTC, closed without merging